/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Xqq's Blog",
  "description": "网络空间无限宽广",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.svg"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "bgImage": "/background.svg",
        "bgImageStyle": {
          "height": "350px"
        },
        "readingShow": "top"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-67c2c25e",
      "path": "/"
    },
    {
      "title": "Webpack学习",
      "frontmatter": {
        "title": "Webpack学习",
        "date": "2024-08-28T00:00:00.000Z",
        "sidebar": "auto",
        "categories": [
          "webpack"
        ],
        "tags": [
          "webpack",
          "学习文档"
        ],
        "readingShow": "top"
      },
      "regularPath": "/views/Webpack/1.html",
      "relativePath": "views/Webpack/1.md",
      "key": "v-6affa7a3",
      "path": "/views/Webpack/1.html"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline",
        "readingShow": "top"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "webpack Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/webpack/",
      "key": "v-b53ec9e8",
      "path": "/tag/webpack/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "学习文档 Tags",
        "readingShow": "top"
      },
      "regularPath": "/tag/%E5%AD%A6%E4%B9%A0%E6%96%87%E6%A1%A3/",
      "key": "v-1d2ef560",
      "path": "/tag/学习文档/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "webpack Categories",
        "readingShow": "top"
      },
      "regularPath": "/categories/webpack/",
      "key": "v-4b927980",
      "path": "/categories/webpack/"
    }
  ],
  "themeConfig": {
    "type": "blog",
    "fullscreen": true,
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "分类"
      },
      "tag": {
        "location": 3,
        "text": "标签"
      },
      "socialLinks": [
        {
          "icon": "reco-github",
          "link": "https://github.com/Tsanfer"
        },
        {
          "icon": "reco-bilibili",
          "link": "https://space.bilibili.com/12167681"
        },
        {
          "icon": "reco-douban",
          "link": "https://www.douban.com/people/219819109"
        },
        {
          "icon": "reco-twitter",
          "link": "https://twitter.com/a1124851454"
        },
        {
          "icon": "reco-mail",
          "link": "mailto:a1124851454@gmail.com"
        }
      ]
    },
    "nav": [
      {
        "text": "主页",
        "link": "/",
        "icon": "reco-home"
      }
    ],
    "subSidebar": "auto",
    "record": "蜀ICP备20005033号-2",
    "recordLink": "https://beian.miit.gov.cn/",
    "cyberSecurityRecord": "川公网安备 51110202000301号",
    "cyberSecurityLink": "http://www.beian.gov.cn/",
    "startYear": "2020",
    "lastUpdated": "最后更新时间",
    "author": "XQQ",
    "authorAvatar": "/avatar.svg",
    "mode": "auto",
    "smooth": "true",
    "valineConfig": {}
  }
}