/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "webpack": {
      "key": "webpack",
      "scope": "tags",
      "path": "/tag/webpack/",
      "pageKeys": [
        "v-6affa7a3"
      ]
    },
    "学习文档": {
      "key": "学习文档",
      "scope": "tags",
      "path": "/tag/学习文档/",
      "pageKeys": [
        "v-6affa7a3"
      ]
    }
  },
  "categories": {
    "webpack": {
      "key": "webpack",
      "scope": "categories",
      "path": "/categories/webpack/",
      "pageKeys": [
        "v-6affa7a3"
      ]
    }
  },
  "timeline": {}
}